[package]
name = "localhost"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = "0.13.3"
http = "0.2.11"
mio = { version = "0.8.9", features = ["net", "os-poll"] }
serde = "1.0"
walkdir = "2"
